# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "mem_sleep_default=deep" ]; # Enable real deepsleep suspend

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/b9edb32f-fb40-4d59-8abe-b187c88667d6";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/e2d53876-3fdc-486a-a354-ec834b256e43";

  fileSystems."/boot/efi" =
    {
      device = "/dev/disk/by-uuid/502E-A0DC";
      fsType = "vfat";
    };

  swapDevices = [{
    device = "/dev/disk/by-partuuid/c231f5ef-0f45-4e96-87e9-76ed935e8332";
    randomEncryption = true;
  }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
